---
- name: This is install Docker 
  hosts: all
  become: yes 

  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: latest

  - name: Start Docker
    service: 
      name: docker
      state: started
      enabled: yes  
  - name: Add user in Docker group
    user:
      name: ubuntu         # Replace with your actual user if different
      groups: docker       # Add to the docker group
      append: yes          # Keep existing groups

  - name: Pull nginx image from Docker Hub
    community.docker.docker_image:     #module to pull the Docker image
        name: ganeshmestry21/my-django-note-app
        source: pull

  - name: Run Docker Image
    community.docker.docker_container:
        name: my-django-note-app
        image: ganeshmestry21/my-django-note-app
        state: started
        restart_policy: always
        published_ports: 
          - "8000:8000"

    

